service: products

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  # environment:
  #   RDS_HOST: ${ssm:/products-api/RDS_HOST}
  #   RDS_USER: ${ssm:/products-api/RDS_USER}
  #   RDS_PASSWORD: ${ssm:/products-api/RDS_PASSWORD}
  #   RDS_DATABASE: ${ssm:/products-api/RDS_DATABASE}
  #   RDS_PORT: ${ssm:/products-api/RDS_PORT}
  #   AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  createProduct:
    handler: handler.createProduct
    events:
      - http:
          path: products
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-db:connect
          # - secretsmanager:GetSecretValue
          # - ssm:GetParameter
        Resource: "*"

  updateProduct:
    handler: handler.updateProduct
    events:
      - http:
          path: products/{id}
          method: put
    iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-db:connect
        Resource: "*"

  deleteProduct:
    handler: handler.deleteProduct
    events:
      - http:
          path: products/{id}
          method: delete
    iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-db:connect
        Resource: "*"

  getAllProducts:
    handler: handler.getAllProducts
    events:
      - http:
          path: products
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-db:connect
        Resource: "*"

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

resources:
  Resources:
    PostgresDB:
      Type: AWS::RDS::DBInstance
      Properties:
        DBInstanceIdentifier: postgres-db
        Engine: postgres
        EngineVersion: "13.7"
        DBInstanceClass: db.t3.micro
        AllocatedStorage: 20
        StorageType: gp2
        PubliclyAccessible: false
        MasterUsername: postgres #!Sub "${ssm:/postgres-api/RDS_USER}"
        MasterUserPassword: postgres #!Sub "${ssm:/postgres-api/RDS_PASSWORD}"
        VPCSecurityGroups:
          - sg-xxxxxxxxxxxxxxxxx # Replace with your actual security group ID
        DBSubnetGroupName: postgres-db-subnet-group # Ensure this exists in your AWS setup
        MultiAZ: false
        BackupRetentionPeriod: 7
        DeletionProtection: false

    # DBSecret:
    #   Type: AWS::SecretsManager::Secret
    #   Properties:
    #     Name: db-credentials
    #     SecretString: !Sub |
    #       {
    #         "username": "${ssm:/products-api/RDS_USER}",
    #         "password": "${ssm:/products-api/RDS_PASSWORD}"
    #       }
